### ISSUE TITLE
#15 [Docs] RestDocs 적용 

### ISSUE THREAD

**Issue by hipopotamus** [codeStatesStudyProject/TravelPlanRepo#31]
## Expected Behavior

  1. RestDocs를 사용해 API를 문서화 할 수 있는 환경 설정

**Comment by Grooomit** [comment]
Rest docs는 docs 가 아니라 feat 으로 들어가나요?

**Comment by hipopotamus** [comment]
설정만 만드는거면 docs가 맞는거 같긴하넹요
